### ISSUE TITLE
能更新下首页文档吗？ 应该需要引用 CacheManagementStackExchangeRedisModule 这个模块吧

### ISSUE THREAD

**Issue by Lflying-NRSoft** [EasyAbp/CacheManagement#20]
能更新下首页文档吗？ 应该需要引用 CacheManagementStackExchangeRedisModule 这个模块吧

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/110281915-88f10780-8018-11eb-9148-595f7d535e07.png)

**Comment by Lflying-NRSoft** [comment]
哦，好的，那我再实现一个默认空的实现类，现在是不引用就直接报错了。
