### ISSUE TITLE
An error ocurred when i visit Menu CacheItems page

### ISSUE THREAD

**Issue by zhchlmm** [EasyAbp/CacheManagement#8]
I have installed all packages followed the steps accordding to the `Getting Started` section, then add a migration and update database, but when i visit CacheItems page, I got an error.

Is there something wrong? can you help me to resolve it.
Thanks!

trace log: 
> `2020-03-30 20:37:52.917 +08:00 [INF] Request starting HTTP/2.0 GET https://localhost:44323/api/app/cacheItem?sorting=displayName%20asc&skipCount=0&maxResultCount=10 application/json 
> 2020-03-30 20:37:52.924 +08:00 [INF] Executing endpoint 'EasyAbp.CacheManagement.CacheItems.CacheItemAppService.GetListAsync (EasyAbp.CacheManagement.Application)'
> 2020-03-30 20:37:52.929 +08:00 [INF] Route matched with {action = "GetList", controller = "CacheItem", area = "", page = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[EasyAbp.CacheManagement.CacheItems.Dtos.CacheItemDto]] GetListAsync(Volo.Abp.Application.Dtos.PagedAndSortedResultRequestDto) on controller EasyAbp.CacheManagement.CacheItems.CacheItemAppService (EasyAbp.CacheManagement.Application).
> 2020-03-30 20:37:52.971 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
> 2020-03-30 20:37:52.974 +08:00 [ERR] {
>   "code": null,
>   "message": "对不起,在处理你的请求期间,产生了一个服务器内部错误!",
>   "details": null,
>   "validationErrors": null
> }
> 2020-03-30 20:37:52.975 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.CacheItemAppServiceProxy -> EasyAbp.CacheManagement.CacheItems.StackExchangeRedisCacheItemManager.
> Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.CacheItemAppServiceProxy -> EasyAbp.CacheManagement.CacheItems.StackExchangeRedisCacheItemManager.
>  ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Caching.Distributed.IDistributedCache, Volo.Abp.Caching.IDistributedCacheKeyNormalizer, Volo.Abp.Threading.ICancellationTokenProvider, Microsoft.Extensions.Configuration.IConfiguration)' on type 'StackExchangeRedisCacheItemManager'.
>  ---> EasyAbp.CacheManagement.CacheItems.DistributedCacheProviderInvalidException: Error in the application.
>    at EasyAbp.CacheManagement.CacheItems.StackExchangeRedisCacheItemManager..ctor(IDistributedCache distributedCache, IDistributedCacheKeyNormalizer keyNormalizer, ICancellationTokenProvider cancellationTokenProvider, IConfiguration configuration)
>    at lambda_method(Closure , Object[] )
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
>    --- End of inner exception stack trace ---
>    at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
>    at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
>    at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
>    --- End of inner exception stack trace ---
>    at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
>    at Autofac.Core.Resolving.InstanceLookup.Execute()
>    at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
>    at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
>    at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
>    at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
>    at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
>    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> 2020-03-30 20:37:52.977 +08:00 [ERR] ---------- Exception Data ----------
> 2020-03-30 20:37:52.978 +08:00 [ERR] ActivatorChain = Castle.Proxies.CacheItemAppServiceProxy -> EasyAbp.CacheManagement.CacheItems.StackExchangeRedisCacheItemManager`

**Comment by gdlcf88** [comment]
Have you solved it? The installation method is complex, I think you should try again.

**Comment by zhchlmm** [comment]
I dont solved it，I just followed the steps to install the module and dont kown what was wrong.

I will have a try , If this problem is solved i will update this issue .


Thank you for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Super"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 下午2:56
收件人: "EasyAbp/CacheManagement"<CacheManagement@noreply.github.com&gt;; 
抄送: "张涛"<zhchlmm@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [EasyAbp/CacheManagement] An error ocurred when i visit Menu CacheItems page (#8)





 
Have you solved it? The installation method is complex, I think you should try again.

**Comment by gdlcf88** [comment]
Could you please provide a git repository to reproduce it?

**Comment by gdlcf88** [comment]
Could you please provide a git repository to reproduce it?

**Comment by zhchlmm** [comment]
> Could you please provide a git repository to reproduce it?

Thanks for your reply.
I  will try to reproduce it  in next few days, if the problem still exists, i will provide a git repository.

**Comment by zhchlmm** [comment]
please [check out this repo](https://github.com/zhchlmm/EasyAbpCacheManagementDemo) to reproduce it.

I have upgraded abp to v2.9 and followed the steps of EasyAbp.CacheManagement except for MongoDB and StackExchangeRedis modules.

**Comment by gdlcf88** [comment]
Your solution is not using StackExchangeRedis.

**Comment by zhchlmm** [comment]
Thanks, I have installed StackExchangeRedis module and confirmed that your are right.
I thought the cache stores in memory as default.

**Comment by gdlcf88** [comment]
> Thanks, I have installed StackExchangeRedis module and confirmed that your are right.
> I thought the cache stores in memory as default.

I'm not sure if it could be implemented because the CacheManagement module's features depend on senior API. I hope you'll have a try when you're free.
